#*****************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# ethmacvcu118.tcl: Tcl script for re-creating project 'ethernetmacphy'
#
# Generated by Vivado on Mon Jul 30 14:10:27 +0200 2018
# IP Build 2256618 on Thu Jun 14 22:10:49 MDT 2018
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "vcu1525project"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "ethmacvcu1525.tcl"

#Set and make the output directory where all the generated files and reports will be stored
set outputDir $origin_dir/../project_flow/${_xil_proj_name_}
file mkdir $outputDir

#create project
create_project ${_xil_proj_name_} $outputDir -part xcvu9p-fsgd2104-2L-e -force

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]


# Set project properties
set obj [current_project]
set_property -name "board_part" -value "xilinx.com:vcu1525:part0:1.1" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj


#Project op level file
add_files $origin_dir/../../../sources/vhdl/implementation/xilinx/vcu1525/top/gmactop.vhd

#LED files
add_files $origin_dir/../../../sources/vhdl/rtl/ledblinker/ledflasher.vhd
add_files $origin_dir/../../..//sources/vhdl/implementation/xilinx/vcu1525/partialreconfig/partialblinker.vhd


#MAC + PHY 1
add_files $origin_dir/../../../sources/vhdl/implementation/xilinx/vcu1525/top/gmacqsfp1top.vhd

#MAC + PHY 2
add_files $origin_dir/../../../sources/vhdl/implementation/xilinx/vcu1525/top/gmacqsfp2top.vhd

#Packet ring buffers
add_files $origin_dir/../../../sources/vhdl/rtl/ringbuffer/packetramsp.vhd
add_files $origin_dir/../../../sources/vhdl/rtl/ringbuffer/packetringbuffer.vhd
add_files $origin_dir/../../../sources/vhdl/rtl/ringbuffer/packetstatusram.vhd

#L-BUS <=> AXIS
add_files $origin_dir/../../../sources/vhdl/rtl/lbustoaxis/lbustoaxis.vhd

#AXIS => L-BUS
add_files $origin_dir/../../../sources/vhdl/rtl/lbustoaxis/mapaxisdatatolbus.vhd
add_files $origin_dir/../../../sources/vhdl/rtl/lbustoaxis/maptkeeptomty.vhd
add_files $origin_dir/../../../sources/vhdl/rtl/lbustoaxis/lbustxaxisrx.vhd

#L-BUS => AXIS
add_files $origin_dir/../../../sources/vhdl/rtl/lbustoaxis/maplbusdatatoaxis.vhd
add_files $origin_dir/../../../sources/vhdl/rtl/lbustoaxis/mapmtytotkeep.vhd
add_files $origin_dir/../../../sources/vhdl/rtl/lbustoaxis/lbusrxaxistx.vhd

#UDP Server (APP Module)
add_files $origin_dir/../../../sources/vhdl/rtl/udp/macinterface/macifudpserver.vhd
add_files $origin_dir/../../../sources/vhdl/rtl/udp/macinterface/macifudpreceiver.vhd
add_files $origin_dir/../../../sources/vhdl/rtl/udp/macinterface/macifudpsender.vhd

#ARP (APP Module) 
add_files $origin_dir/../../../sources/vhdl/rtl/arp/arpmodule.vhd
add_files $origin_dir/../../../sources/vhdl/rtl/arp/arpreceiver.vhd

#Multiplexer Module
add_files $origin_dir/../../../sources/vhdl/rtl/udp/macinterface/axisfabricmultiplexer.vhd
add_files $origin_dir/../../../sources/vhdl/rtl/udp/macinterface/axisthreeportfabricmultiplexer.vhd

#IP Interconnect
add_files $origin_dir/../../../sources/vhdl/rtl/udp/ipcomms.vhd

# Add Xilinx IP Blocks

#MAC + PHY 1
add_files $origin_dir/../../../sources/ip/vcu1525/ethmacphy100gqsfp14x/EthMACPHY100GQSFP14x.xci

#MAC + PHY 2
add_files $origin_dir/../../../sources/ip/vcu1525/ethmacphy100gqsfp24x/EthMACPHY100GQSFP24x.xci

#AXI FIFO PACKER BUFFER
add_files $origin_dir/../../../sources/ip/vcu1525/axispacketbufferfifo/axispacketbufferfifo.xci

# Clock Generator
add_files $origin_dir/../../../sources/ip/vcu1525/clockgen100mhz/clockgen100mhz.xci


#Debug files
#AXIS ILA
add_files $origin_dir/../../../sources/ip/vcu1525/axisila/axisila.xci

#AXIS ILA
add_files $origin_dir/../../../sources/ip/vcu1525/resetvio/resetvio.xci

# Add constraints
create_fileset -constrset ethconstrs

add_files -fileset ethconstrs $origin_dir/../../../sources/constraints/xilinx/vcu1525/gmactop.xdc




# Start processing
puts "INFO: Project Flow is starting..."

# Run synthesis
set_property constrset ethconstrs [get_runs synth_1]

#launch_runs synth_1
#wait_on_run synth_1

#  Run implementation
update_compile_order -fileset sources_1
set_property constrset ethconstrs [get_runs impl_1]

set_property STEPS.PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]

#launch_runs impl_1 -to_step write_bitstream
#wait_on_run impl_1
#puts "implementation done!"

puts "INFO: Project Flow has completed successfully"
