#*****************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# ethmacvcu118.tcl: Tcl script for re-creating project 'ethernetmacphy'
#
# Generated by Vivado on Mon Jul 30 14:10:27 +0200 2018
# IP Build 2256618 on Thu Jun 14 22:10:49 MDT 2018
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

#Set and make the output directory where all the generated files and reports will be stored
set outputDir $origin_dir/../project_flow/output_files
file mkdir $outputDir

#create project
create_project vcu118project $outputDir -part xcvu9p-flga2104-2L-e -force

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]


# Set project properties
set obj [current_project]
set_property -name "board_part" -value "xilinx.com:vcu118:part0:2.0" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.board_id" -value "vcu118" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.uses_pr" -value "1" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/vcu118project.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/vcu118project.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "34" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "34" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "34" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "34" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "34" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "34" -objects $obj
set_property -name "webtalk.xcelium_export_sim" -value "8" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "34" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

#Project op level file
add_files $origin_dir/../sources/vhdl/implementation/xilinx/vcu118/top/gmactop.vhd

#LED files
add_files $origin_dir/../sources/vhdl/rtl/ledblinker/ledflasher.vhd
add_files $origin_dir/../sources/vhdl/rtl/ledblinker/partialblinker.vhd


#MAC + PHY 1
add_files $origin_dir/../sources/vhdl/implementation/xilinx/vcu118/top/gmacqsfp1top.vhd

#MAC + PHY 2
add_files $origin_dir/../sources/vhdl/implementation/xilinx/vcu118/top/gmacqsfp2top.vhd

#Packet ring buffers
add_files $origin_dir/../sources/vhdl/rtl/ringbuffer/packetramsp.vhd
add_files $origin_dir/../sources/vhdl/rtl/ringbuffer/packetringbuffer.vhd
add_files $origin_dir/../sources/vhdl/rtl/ringbuffer/packetstatusram.vhd

#L-BUS <=> AXIS
add_files $origin_dir/../sources/vhdl/rtl/lbustoaxis/lbustoaxis.vhd

#AXIS => L-BUS
add_files $origin_dir/../sources/vhdl/rtl/lbustoaxis/mapaxisdatatolbus.vhd
add_files $origin_dir/../sources/vhdl/rtl/lbustoaxis/maptkeeptomty.vhd
add_files $origin_dir/../sources/vhdl/rtl/lbustoaxis/lbustxaxisrx.vhd

#L-BUS => AXIS
add_files $origin_dir/../sources/vhdl/rtl/lbustoaxis/maplbusdatatoaxis.vhd
add_files $origin_dir/../sources/vhdl/rtl/lbustoaxis/mapmtytotkeep.vhd
add_files $origin_dir/../sources/vhdl/rtl/lbustoaxis/lbusrxaxistx.vhd

#UDP Server (APP Module)
add_files $origin_dir/../sources/vhdl/rtl/udp/macinterface/macifudpserver.vhd
add_files $origin_dir/../sources/vhdl/rtl/udp/macinterface/macifudpreceiver.vhd
add_files $origin_dir/../sources/vhdl/rtl/udp/macinterface/macifudpsender.vhd

#ARP (APP Module) 
add_files $origin_dir/../sources/vhdl/rtl/arp/arpmodule.vhd
add_files $origin_dir/../sources/vhdl/rtl/arp/arpreceiver.vhd

#Multiplexer Module
add_files $origin_dir/../sources/vhdl/rtl/udp/macinterface/axisfabricmultiplexer.vhd
add_files $origin_dir/../sources/vhdl/rtl/udp/macinterface/axisthreeportfabricmultiplexer.vhd

#IP Interconnect
add_files $origin_dir/../sources/vhdl/rtl/udp/ipcomms.vhd

# Add Xilinx IP Blocks

#MAC + PHY 1
add_files $origin_dir/../sources/ip/vcu118/ethmacphy100gqsfp14x/EthMACPHY100GQSFP14x.xci

#MAC + PHY 2
add_files $origin_dir/../sources/ip/vcu118/ethmacphy100gqsfp24x/EthMACPHY100GQSFP24x.xci

#AXI FIFO PACKER BUFFER
add_files $origin_dir/../sources/ip/vcu118/axispacketbufferfifo/axispacketbufferfifo.xci

# Clock Generator
add_files $origin_dir/../sources/ip/vcu118/clockgen100mhz/clockgen100mhz.xci

# Add constraints
create_fileset -constrset ethconstrs

add_files -fileset ethconstrs $origin_dir/../sources/constraints/xilinx/vcu118/gmactop.xdc




# Start processing
puts "INFO: Project Flow is starting..."

# Run synthesis
set_property constrset ethconstrs [get_runs synth_1]

launch_runs synth_1
wait_on_run synth_1

#  Run implementation
#update_compile_order -fileset sources_1
#set_property constrset ethconstrs [get_runs impl_1]

#set_property STEPS.PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]

#launch_runs impl_1 -to_step write_bitstream
#wait_on_run impl_1
puts "implementation done!"

puts "INFO: Project Flow has completed successfully"
